version: "3.7"
services:
    frontend:
       container_name: debunker-frontend
       build: 
        dockerfile: docker/Dockerfile
        context: .
       ports:
           - "80:80"
       networks:
         - debunker-net
networks:
  debunker-net:
    external: true
